### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by titsitits** [diegovalsesia/gcdn#5]
Hi,

Your method seems promising, and I would like to know if you plan to add an open-source license (such as MIT or Apache-2.0) to your repo so it can be used elsewhere ?
If so, I plan to refer to it in my own project: https://github.com/titsitits/open-image-restoration
and I'll try to integrate your method (maybe replace NLRN by yours after some tests) to my restoration pipeline.

(it's very easy to add a license to your repo, you just need to upload a license.md file like this one: https://github.com/titsitits/open-image-restoration/blob/master/LICENSE.md 
file raw version: https://raw.githubusercontent.com/titsitits/open-image-restoration/master/LICENSE.md )

Best regards,
Mickaël

**Comment by diegovalsesia** [comment]
Hi, we updated the license information. We went with an MIT License.

**Comment by titsitits** [comment]
Super cool, I will intensify my tests with your algorithm on my images then !
